# Step 1. Create all tables first
# Create homeowners table
CREATE TABLE IF NOT EXISTS homeowners(
    HOID BIGINT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    email VARCHAR(100) PRIMARY KEY UNIQUE NOT NULL,
    password VARCHAR(16) NOT NULL,
    phone INT NOT NULL,
    creditcard BIGINT UNSIGNED,
    bankaccount BIGINT UNSIGNED
);

# Create the homes table
CREATE TABLE IF NOT EXISTS homes(
    HID BIGINT UNSIGNED PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    street VARCHAR(100) NOT NULL,
    city VARCHAR(45) NOT NULL,
    state VARCHAR(21) NOT NULL,
    zip BIGINT UNSIGNED NOT NULL,
    constr_type VARCHAR(45) NOT NULL,
    floors VARCHAR(45) NOT NULL,
    h_sq_ft BIGINT UNSIGNED NOT NULL,
    y_sq_ft BIGINT UNSIGNED NOT NULL,
    plant_types VARCHAR(45) NOT NULL
);

# Create the Owns Table
CREATE TABLE IF NOT EXISTS owns(
    OID BIGINT UNSIGNED PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    HOID BIGINT UNSIGNED NOT NULL,
    HID BIGINT UNSIGNED NOT NULL
);

# Create service_professionals table
CREATE TABLE IF NOT EXISTS service_pros(
    SPID BIGINT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    b_name VARCHAR(45) NOT NULL,
    email VARCHAR(100) UNIQUE PRIMARY KEY NOT NULL ,
    password VARCHAR(16) NOT NULL,
    creditcard BIGINT UNSIGNED,
    bankaccount BIGINT UNSIGNED,
    services BIGINT UNSIGNED
);

# Create services table
CREATE TABLE IF NOT EXISTS services(
    SID BIGINT UNSIGNED PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    s_type VARCHAR(100) NOT NULL,
    s_price BIGINT UNSIGNED NOT NULL
);

# create provides table
CREATE TABLE IF NOT EXISTS provides(
    PID BIGINT UNSIGNED PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    SPID BIGINT UNSIGNED NOT NULL,
    SID BIGINT UNSIGNED NOT NULL
);

# Step 2. Add constraints in this section

# Step 3. Save changes
COMMIT;